### ISSUE TITLE
Error when current-context is empty

### ISSUE THREAD

**Issue by TedSpinks** [TedSpinks/kube-ahoy#1]
When current-context contains an empty string, the following error occurs:

```
Traceback (most recent call last):
  File "/usr/local/bin/ka", line 718, in <module>
    main()
  File "/usr/local/bin/ka", line 715, in main
    print("Current " + kubeconfig.summarize_context(kubeconfig.current_context, 2))
  File "/usr/local/bin/ka", line 294, in summarize_context
    return summary
UnboundLocalError: local variable 'summary' referenced before assignment
```

**Comment by TedSpinks** [comment]
This was fixed in https://github.com/TedSpinks/kube-ahoy/commit/cab12c729392ee630f003af10e41f7f85a2ba4d3
